### PR TITLE
Replacing rvm with rbenv in readme

### PR DESCRIPTION
**Pull request by kayrocesar**
- Replacing rvm with rbenv in readme 
- Resolve Issue : [#1425 -  Installation error on dev setup](https://github.com/houdiniproject/houdini/issues/1425)

Co-Authored-By: [Victor Cabral](https://github.com/victordscabral)
Co-Authored-By: [João](https://github.com/joaobisi)

### CODE REVIEW

**Review by wwahammy — CHANGES_REQUESTED** [review]
@kayrocesar, @victordscabral, @joaobisi thank you for the contribution! This is a really good start.

I left one specific comment to be addressed. Additionally, to improve clarity in git history, please remove the formatting changes.

Thanks a lot and welcome to the Houdini Project!

**Comment by kayrocesar** [comment]
Done.
Can you review again? @wwahammy

**Review by wwahammy — CHANGES_REQUESTED** [review]
Hi all, thanks for the changes. Unfortunately, I'm still seeing a lot of formatting modifications. You can see them if you go
to https://github.com/houdiniproject/houdini/pull/1430/files. The goal should be to only include changes that are related
to the change you want to make. Here's a few tips on this:

* Recreating the original formatting can be a pain- a better idea is to checkout the old version of the file before
before you started making changes. You can do this by calling `git checkout HEAD~2 -- README.md`. This tells git
to give you the file as it was two commits before HEAD (which is the current place in the git history).
* Once you have the original formatting, make the edits you want made and nothing more.
* Make sure your editor isn't autoformatting the whole file; I think that's probably what's happening. There's usually
a way to turn it off in your editor; alternatively, use an editor without autoformatting.

Once you've cleaned up the file, I'll be happy to review and merge.

**Comment by victordscabral** [comment]
@wwahammy. I believe we have solved the problem. Can you review?

**Review by wwahammy — APPROVED** [review]
Looks good!

**Comment by wwahammy** [comment]
Oops, forgot to merge this! :laughing:

**Pull request merged**
