### PR TITLE
Fix donations for Houdini

### PR DESCRIPTION
**Pull request by wwahammy**
There were a number of interconnected issues with the donation system. This is a quick fix for them but there are additional ones I am sure.

This seems to work on the pretty path but not quite sure how badly it works when there are errors

Depends on #1065
Depends on #1064

### CODE REVIEW

**Comment by BenSturmfels** [comment]
Confirming that this fixes #1050! It doesn't fix #1067 or #1069.

**Review by clarissalimab — APPROVED** [review]
:rocket:

**Comment by wwahammy** [comment]
@clarissalimab, I'm rerequesting review because I made a few more changes. I doubt it has any real effect on the end result but please look them over since I *THINK* this is passing... we'll see in a few minutes i guess!

**Comment by wwahammy** [comment]
:fireworks:

**Review by clarissalimab — APPROVED** [review]
It looks good again!

**Comment by BenSturmfels** [comment]
Brilliant! Thanks @clarissalimab and @wwahammy for your work on this!

**Pull request merged**
