### PR TITLE
Adding getting started with wsl2 into docs

### LINKED ISSUE #1545: [FEATURE] Houdini installation and configuration documentation with WSL2
Myself and a few other colleagues had some issues setting up the development environment using WSL2.

The goal of this issue is to create a step-by-step documentation for installing and configuring Houdini on WSL2 (Windows Subsystem for Linux), in order to make the process easier for users and ensure that the installation is done correctly. The documentation will cover everything from preparing the environment with the necessary software installations until configuring Stripe API keys for development. The intention of this documentation is to be useful for both novice and experienced developers working with WSL2.

### PR DESCRIPTION
**Pull request by eduardomr**
Closes #1545

### CODE REVIEW

**Review by wwahammy — COMMENTED** [review]
It looks fine to me! Did you verify this actually all works? :smile:

**Comment by wwahammy** [comment]
Hey all, it looks like the markdown lint didn't quite work. The reason is probably because you, reasonably, copied this info from README.md and we specifically exclude README.md from linting right now.

We won't worry about that this time but, in another PR, I encourage you to remove the exclusion for README.md and correct all of the markdown linting issues in both files.

**Comment by eduardomr** [comment]
> Hey all, it looks like the markdown lint didn't quite work. The reason is probably because you, reasonably, copied this info from README.md and we specifically exclude README.md from linting right now.
> 
> We won't worry about that this time but, in another PR, I encourage you to remove the exclusion for README.md and correct all of the markdown linting issues in both files.

I apologize in advance if this question seems too basic, but I couldn't locate the exact file where this exclusion is being specified.

Could you please guide me to the file responsible for removing the README file from the lint configuration?

**Comment by wwahammy** [comment]
@eduardomr I just realized that the markdown linting config is not easy to modify. Could you file an issue which mentions we need to lint all of the markdown files in the repo and eliminate all of the exclusions? As part of that, you should mention it's not clear where the markdown linting exclusions are set.

**Comment by eduardomr** [comment]
@wwahammy Okay! i'll open the issue

**Pull request merged**
