### PR TITLE
Remove exclusionary term related to custom fields

### LINKED ISSUE #460: [BUG] Exclusionary term related to Custom Fields
Currently Houdini includes the term CustomFieldMaster in the source code. Master is an offensive term and should be removed from Houdini. The Houdini project community apologizes for its legacy use.

Similar to the work on #456, changes which need to be made include:

* renaming the `CustomFieldMaster` class to `CustomFieldDefinition`
* renaming the `custom_field_masters` database table
* renaming the `CustomFieldMasterController` class and  any routes referring to it.
* finding any place where the `custom_field_masters` table is used in the source code and rename it to `custom_field_definitions`

There may be other legacy uses which must be evaluated and found.

### PR DESCRIPTION
**Pull request by heronsousa**
## Description
Houdini has some offensive terms that should be removed from the project.

## Issue
Closes #460

### CODE REVIEW

**Comment by wwahammy** [comment]
Hey there @heronsousa, thanks for this PR! This is some great work and will make Houdini more inclusive.

A few things to consider:

* Please rebase this on the latest version of `main` branch from this repo. There will be a few conflicts you'll need to deal with. an important notes on that conflicts:
  * Make sure to use the later version (versions names look like dates) in `db/schema.rb` file on the line that reads: `ActiveRecord::Schema.define(version: ...) do`

* You need to change line 6 of `spec/factories/custom_field_definitions.rb` to read `factory :custom_field_definition do`
* Make sure to run `bin/rails spec` and make sure all of the tests still pass.
* Make sure to run `rubocop -a` to autocorrect any formatting bugs. Also, if it has any formatting issues that can't be automatically fixed, make sure to fix them yourself. (There shouldn't be any I don't think but better safe than sorry)

* After you've done all that, you'll need to force push to your branch `git push -f` because the rebase will have rewritten the history.

Once you've done that, please request a review so we know to check it out and hopefully get it merged!

Overall, fantastic job and extremely helpful.

**Comment by wwahammy** [comment]
Oh, one other thing: you should edit the description above and add `Closes ` before #460 in the description. That tells Github to automatically close that issue when this PR is merged.

**Comment by heronsousa** [comment]
Okay, i'll fix it. Thanks for the explanation!

**Comment by heronsousa** [comment]
I'm sorry @wwahammy, didn't your answer. I'm having trouble with this one. Do you have any tip on what it might be? I was searching on api where this endpoint is defined, but I didn't succeed.
image

**Comment by wwahammy** [comment]
@heronsousa thanks for letting me know about the issue! I corrected the bugs as far as I can tell and I've submitted a PR to your branch to merge in the fixes.

**Comment by heronsousa** [comment]
@wwahammy thank you so much for your help, didn't realize that the endpoints were generated dynamic. Sorry for taking so much time to resolve this issue 😅

**Comment by wwahammy** [comment]
I've merged the PR. Thanks for all  the help @heronsousa. We'd love if you'd do the same thing changes to tag_masters.

**Pull request merged**
