### PR TITLE
Fix translations

### LINKED ISSUE #1061: [BUG] Missing translations on Donate Form in dev
(Transferring this from Discussion #1048  to an Issue not that @wwahammy has confirmed it's an issue. Sorry, appears that the "Create issue from discussion" button only transfers the first post".)

<div type='discussions-op-text'>

<sup>Originally posted by **BenSturmfels** March 16, 2022</sup>
Hi Folks,
After running up a development environment as per the README.md, if I go to the "Donate Form Builder" and click on the blue "Donate" button, I see a form that has lots of text like:

`[missing "en.nonprofits.donate.payment.card.submit" translation]`

Screen Shot 2022-03-16 at 17 29 46

Have I missed a step somewhere?</div>

### PR DESCRIPTION
**Pull request by wwahammy**
Closes #1061

This addresses the immediate translation issues noticed in #1061. The problem was that ReactIntl expects messages provided in dot-object notation while i18n-js expects messages provided as nested objects. I think it could use a bit more testing however.

To better explain what's going on, ReactIntl expects message objects for a given locale like this:

```json
{
   activerecord.error.some_error: "This is a some error message"
}
```

On the other hand, i18n-js expects it like:

```json
{
  activerecord: {
    error: {
       some_error: "This is some error message"
    }
  }
}
```

### CODE REVIEW

**Comment by wwahammy** [comment]
@BenSturmfels this is a tentative fix for the translation issue.

**Review by clarissalimab — APPROVED** [review]

**Comment by BenSturmfels** [comment]
Awesome! Thanks @wwahammy, that's working well in my testing.

**Comment by BenSturmfels** [comment]
@wwahammy - would be wonderful to get this one merged if possible as it will mean we can switch our trial deployment back to the main branch.

**Comment by wwahammy** [comment]
@BenSturmfels There's one test here that seems to fail that I haven't had time to debug. Unfortunately, I finallly was caught by COVID so I couldn't do anything this week until now and I could be slow working through things in coming days as i recover. Sorry about the delay and thanks for the patience.

**Comment by BenSturmfels** [comment]
@wwahammy sorry to hear that! Hope you're doing ok and are feeling better soon. Thanks for all your help.

**Comment by wwahammy** [comment]
@BenSturmfels my hope is that I can address dig into this sometime after work tomorrow. I'm just getting back into the swing of things after COVID.

**Comment by BenSturmfels** [comment]
Thanks @wwahammy, don't feel under any pressure on our behalf. We really appreciate all you've done to help already. :)

**Comment by wwahammy** [comment]
@BenSturmfels I was FINALLY able to find the time to address this! I'll be merging now.

**Pull request merged**
